import type { PageStrings } from "@/lib/i18n-page";

/**
 * 落地页（/）页面级词条：zh/en 双语。
 * 通过 makePageT 与全局词典合并（本文件优先），无需改动 lib/i18n.ts。
 */
export const LANDING_STRINGS: PageStrings = {
  zh: {
    "landing.nav.features": "功能",
    "landing.nav.modules": "模块",
    "landing.nav.how": "如何使用",
    "landing.nav.login": "登录",
    "landing.nav.start": "免费开始",
    "landing.nav.workspace": "进入工作区",

    "landing.hero.kicker": "M0–M10 · 多智能体辅导系统",
    "landing.hero.title.a": "你的私人",
    "landing.hero.title.b": "AI 教师",
    "landing.hero.subtitle":
      "讲解、出题、答疑，全部基于真实教材。十层智能模块协同编排，记住你学过什么，知道下一步该怎么教。",
    "landing.hero.primary": "免费开始",
    "landing.hero.secondary": "已有账号，登录",
    "landing.hero.workspace": "进入工作区",
    "landing.hero.scroll": "向下滚动",
    "landing.hero.vertical": "因材施教 · 有教无类",

    "landing.marquee.1": "苏格拉底式讲解",
    "landing.marquee.2": "CAT 自适应测评",
    "landing.marquee.3": "教材 RAG 检索",
    "landing.marquee.4": "BKT 掌握度追踪",
    "landing.marquee.5": "SM-2 间隔重复",
    "landing.marquee.6": "教材知识图谱",
    "landing.marquee.7": "六模式教学引擎",
    "landing.marquee.8": "长期学习记忆",

    "landing.features.kicker": "功能 / Features",
    "landing.features.title": "一位真正懂教学的 AI",
    "landing.features.subtitle":
      "不只是聊天机器人——每一轮对话背后，都有教学策略、掌握度追踪与教材依据。",
    "landing.features.f1.title": "苏格拉底式讲解",
    "landing.features.f1.desc": "循循善诱的对话式讲解，引导你自己想明白，而不是直接给出答案。",
    "landing.features.f2.title": "智能出题测评",
    "landing.features.f2.desc": "约束出题、三级评分与 CAT 自适应测试，真实检验「学会了没有」。",
    "landing.features.f3.title": "教材 RAG 检索",
    "landing.features.f3.desc": "回答基于你选用的教材内容，概念出处可溯源，拒绝凭空发挥。",
    "landing.features.f4.title": "学习笔记",
    "landing.features.f4.desc": "边学边记，笔记与对话联动，把知识沉淀成你自己的资料库。",
    "landing.features.f5.title": "学情画像",
    "landing.features.f5.desc": "BKT 掌握度追踪与知识图谱可视化，强项弱项一目了然。",
    "landing.features.f6.title": "长期学习编排",
    "landing.features.f6.desc": "从学期目标到今日任务，SM-2 间隔重复帮你对抗遗忘。",

    "landing.modules.kicker": "架构 / Architecture",
    "landing.modules.title": "M0–M10 · 十层智能模块",
    "landing.modules.subtitle": "每一轮对话，都经过一条完整的多智能体编排流水线。",
    "landing.modules.m0.name": "身份基础设施",
    "landing.modules.m0.desc": "用户是谁、数据属于谁、如何安全访问",
    "landing.modules.m1.name": "任务智能",
    "landing.modules.m1.desc": "理解 → 规划 → 工具执行 → 状态更新",
    "landing.modules.m2.name": "学生模型",
    "landing.modules.m2.desc": "学习画像 + BKT 掌握度 + 概念状态",
    "landing.modules.m3.name": "教学引擎",
    "landing.modules.m3.desc": "六模式状态机 + 跨轮教学记忆",
    "landing.modules.m4.name": "测评智能",
    "landing.modules.m4.desc": "三级评分 + 约束出题 + CAT 自适应测试",
    "landing.modules.m5.name": "知识智能",
    "landing.modules.m5.desc": "教材知识图谱 + 概念检索",
    "landing.modules.m6.name": "记忆智能",
    "landing.modules.m6.desc": "有界画像 + 策略聚合，越用越懂你",
    "landing.modules.m7.name": "评估改进",
    "landing.modules.m7.desc": "教学自诊断，让 AI 教师越教越好",
    "landing.modules.m8.name": "交互体验",
    "landing.modules.m8.desc": "表达方式适配每个学生的偏好",
    "landing.modules.m9.name": "学习编排",
    "landing.modules.m9.desc": "目标 → 长期任务 → 周任务 → 今日任务",
    "landing.modules.m10.name": "能力运行时",
    "landing.modules.m10.desc": "技能调用契约与学习证据门",

    "landing.how.kicker": "开始使用 / Getting started",
    "landing.how.title": "三步，开始你的第一课",
    "landing.how.s1.title": "创建账号",
    "landing.how.s1.desc": "注册即得专属学习空间，所有数据完全隔离。",
    "landing.how.s2.title": "提问或选教材",
    "landing.how.s2.desc": "直接使用公共教材，或上传你自己的资料，然后尽管提问。",
    "landing.how.s3.title": "持续进步",
    "landing.how.s3.desc": "系统追踪你的掌握度，自动安排复习与测评。",

    "landing.cta.title": "准备好开始了吗？",
    "landing.cta.subtitle": "免费创建账号，让 AI 教师为你定制第一课。",
    "landing.cta.button": "免费开始",
    "landing.cta.workspace": "进入工作区",

    "landing.footer.docs": "文档",
    "landing.footer.login": "登录",
    "landing.footer.register": "注册",
  },
  en: {
    "landing.nav.features": "Features",
    "landing.nav.modules": "Modules",
    "landing.nav.how": "How it works",
    "landing.nav.login": "Sign in",
    "landing.nav.start": "Get started",
    "landing.nav.workspace": "Open workspace",

    "landing.hero.kicker": "M0–M10 · Multi-agent tutoring",
    "landing.hero.title.a": "Your private",
    "landing.hero.title.b": "AI tutor",
    "landing.hero.subtitle":
      "Explain, quiz, and Q&A — all grounded in real textbooks. Ten intelligence modules work in concert, remember what you've learned, and know how to teach next.",
    "landing.hero.primary": "Get started free",
    "landing.hero.secondary": "Sign in",
    "landing.hero.workspace": "Open workspace",
    "landing.hero.scroll": "Scroll",
    "landing.hero.vertical": "EVERY STUDENT · A TUTOR",

    "landing.marquee.1": "Socratic Tutoring",
    "landing.marquee.2": "CAT Adaptive Testing",
    "landing.marquee.3": "Textbook RAG",
    "landing.marquee.4": "BKT Mastery Tracking",
    "landing.marquee.5": "SM-2 Spaced Repetition",
    "landing.marquee.6": "Knowledge Graph",
    "landing.marquee.7": "Six-Mode Teaching Engine",
    "landing.marquee.8": "Long-Term Memory",

    "landing.features.kicker": "Features",
    "landing.features.title": "An AI that actually teaches",
    "landing.features.subtitle":
      "Not just a chatbot — behind every turn there is pedagogy, mastery tracking, and textbook evidence.",
    "landing.features.f1.title": "Socratic explaining",
    "landing.features.f1.desc":
      "Guided dialogue that helps you figure things out yourself instead of handing you answers.",
    "landing.features.f2.title": "Smart assessment",
    "landing.features.f2.desc":
      "Constrained quiz generation, three-level grading, and CAT adaptive testing that verify real mastery.",
    "landing.features.f3.title": "Textbook RAG",
    "landing.features.f3.desc":
      "Answers grounded in your chosen textbooks, with traceable concept sources — no hallucinated facts.",
    "landing.features.f4.title": "Study notes",
    "landing.features.f4.desc":
      "Take notes as you learn, linked to your conversations, building your own knowledge base.",
    "landing.features.f5.title": "Mastery profile",
    "landing.features.f5.desc":
      "BKT mastery tracking and knowledge-graph visualization make strengths and gaps obvious.",
    "landing.features.f6.title": "Long-term planning",
    "landing.features.f6.desc":
      "From semester goals down to today's tasks, with SM-2 spaced repetition against forgetting.",

    "landing.modules.kicker": "Architecture",
    "landing.modules.title": "M0–M10 · Ten intelligence modules",
    "landing.modules.subtitle": "Every turn runs through a complete multi-agent orchestration pipeline.",
    "landing.modules.m0.name": "Identity",
    "landing.modules.m0.desc": "Who the user is, who owns the data, secure access",
    "landing.modules.m1.name": "Task intelligence",
    "landing.modules.m1.desc": "Understand → plan → execute tools → update state",
    "landing.modules.m2.name": "Student model",
    "landing.modules.m2.desc": "Profile + BKT mastery + concept states",
    "landing.modules.m3.name": "Teaching engine",
    "landing.modules.m3.desc": "Six-mode state machine + cross-turn teaching memory",
    "landing.modules.m4.name": "Assessment",
    "landing.modules.m4.desc": "Three-level grading + constrained quizzing + CAT",
    "landing.modules.m5.name": "Knowledge intelligence",
    "landing.modules.m5.desc": "Textbook knowledge graph + concept retrieval",
    "landing.modules.m6.name": "Memory intelligence",
    "landing.modules.m6.desc": "Bounded profiles + strategy aggregation — knows you better over time",
    "landing.modules.m7.name": "Self-evaluation",
    "landing.modules.m7.desc": "Teaching self-diagnostics so the tutor keeps improving",
    "landing.modules.m8.name": "UX intelligence",
    "landing.modules.m8.desc": "Expression adapted to each student's preferences",
    "landing.modules.m9.name": "Learning orchestration",
    "landing.modules.m9.desc": "Goals → long-term tasks → weekly tasks → today's tasks",
    "landing.modules.m10.name": "Skill runtime",
    "landing.modules.m10.desc": "Skill contracts and the learning-evidence gate",

    "landing.how.kicker": "Getting started",
    "landing.how.title": "Three steps to your first lesson",
    "landing.how.s1.title": "Create an account",
    "landing.how.s1.desc": "Sign up for a private learning space — all data fully isolated.",
    "landing.how.s2.title": "Ask or pick a textbook",
    "landing.how.s2.desc":
      "Use the public textbooks or upload your own materials, then ask anything.",
    "landing.how.s3.title": "Keep improving",
    "landing.how.s3.desc":
      "The system tracks your mastery and schedules reviews and quizzes automatically.",

    "landing.cta.title": "Ready to start?",
    "landing.cta.subtitle": "Create a free account and let your AI tutor tailor the first lesson.",
    "landing.cta.button": "Get started free",
    "landing.cta.workspace": "Open workspace",

    "landing.footer.docs": "Docs",
    "landing.footer.login": "Sign in",
    "landing.footer.register": "Sign up",
  },
};
